title: Imaginative Realities
logo: 
description: Stray thoughts, InfoSec and Anthropology notes
show_downloads: false
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-feed
- jekyll-remote-theme
