title: Imaginative Realities
description: Cyber Security and Stray Thoughts
repository: everydayrain/everydayrain.github.io
github: [metadata]
show_downloads: false
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
