title: Imaginative Realities
logo: 
description: Stray thoughts, InfoSec and Anthropology notes
show_downloads: false
google_analytics:
remote_theme: alshedivat/al-folio
plugins:
- jekyll-feed
- jekyll-remote-theme
