title: Imaginative Realities
description: Cyber Security and Stray Thoughts
repository: everydayrain/christopherbauer.org
github: [metadata]
show_downloads: false
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
  - jekyll-feed
