title: Imaginative Realities
description: Cyber Security and Stray Thoughts
repository: everydayrain/everydayrain.github.io
github: [metadata]
show_downloads: false
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-remote-theme
